export interface QuizQuestion {
  id: string;
  topic: string;
  question: string;
  options: string[];
  correct: string;
}

export const allQuizData: Record<string, QuizQuestion[]> = {
  java: [
    {
      id: "java1",
      topic: "OOP Concepts",
      question: "Which of the following is NOT a pillar of Object-Oriented Programming?",
      options: ["Encapsulation", "Inheritance", "Compilation", "Polymorphism"],
      correct: "Compilation",
    },
    {
      id: "java2",
      topic: "OOP Concepts",
      question: "What is the output of: System.out.println(10 + 20 + \"30\");",
      options: ["102030", "3030", "60", "Error"],
      correct: "3030",
    },
    {
      id: "java3",
      topic: "Collections",
      question: "Which collection class allows duplicate elements?",
      options: ["Set", "HashSet", "ArrayList", "Map"],
      correct: "ArrayList",
    },
    {
      id: "java4",
      topic: "Collections",
      question: "Which interface is implemented by HashMap?",
      options: ["List", "Set", "Map", "Collection"],
      correct: "Map",
    },
    {
      id: "java5",
      topic: "Multithreading",
      question: "Which method is used to start a thread?",
      options: ["run()", "start()", "init()", "begin()"],
      correct: "start()",
    },
    {
      id: "java6",
      topic: "Multithreading",
      question: "What is synchronized keyword used for?",
      options: ["Thread creation", "Thread synchronization", "Thread termination", "Thread priority"],
      correct: "Thread synchronization",
    },
    {
      id: "java7",
      topic: "Exception Handling",
      question: "Which keyword is used to manually throw an exception?",
      options: ["throws", "throw", "try", "catch"],
      correct: "throw",
    },
    {
      id: "java8",
      topic: "Exception Handling",
      question: "Which of these is a checked exception?",
      options: ["NullPointerException", "IOException", "ArithmeticException", "ArrayIndexOutOfBoundsException"],
      correct: "IOException",
    },
    {
      id: "java9",
      topic: "OOP Concepts",
      question: "Can we override static methods in Java?",
      options: ["Yes", "No", "Only in child class", "Depends on modifier"],
      correct: "No",
    },
    {
      id: "java10",
      topic: "Collections",
      question: "Which collection maintains insertion order?",
      options: ["HashSet", "TreeSet", "LinkedHashSet", "Set"],
      correct: "LinkedHashSet",
    },
    {
      id: "java11",
      topic: "OOP Concepts",
      question: "What is the default value of a boolean variable in Java?",
      options: ["true", "false", "null", "0"],
      correct: "false",
    },
    {
      id: "java12",
      topic: "Exception Handling",
      question: "Which block is always executed in try-catch-finally?",
      options: ["try", "catch", "finally", "all of them"],
      correct: "finally",
    },
  ],
  datastructure: [
    {
      id: "ds1",
      topic: "Arrays & Linked Lists",
      question: "What is the time complexity of accessing an element in an array by index?",
      options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
      correct: "O(1)",
    },
    {
      id: "ds2",
      topic: "Arrays & Linked Lists",
      question: "Which data structure uses LIFO principle?",
      options: ["Queue", "Stack", "Array", "Linked List"],
      correct: "Stack",
    },
    {
      id: "ds3",
      topic: "Stacks & Queues",
      question: "In which data structure is FIFO principle used?",
      options: ["Stack", "Tree", "Queue", "Graph"],
      correct: "Queue",
    },
    {
      id: "ds4",
      topic: "Stacks & Queues",
      question: "What is the time complexity of push operation in a stack?",
      options: ["O(1)", "O(n)", "O(log n)", "O(n²)"],
      correct: "O(1)",
    },
    {
      id: "ds5",
      topic: "Trees & Graphs",
      question: "What is the maximum number of children a binary tree node can have?",
      options: ["1", "2", "3", "Unlimited"],
      correct: "2",
    },
    {
      id: "ds6",
      topic: "Trees & Graphs",
      question: "Which traversal visits root node first?",
      options: ["Inorder", "Preorder", "Postorder", "Level order"],
      correct: "Preorder",
    },
    {
      id: "ds7",
      topic: "Sorting & Searching",
      question: "What is the time complexity of Binary Search?",
      options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"],
      correct: "O(log n)",
    },
    {
      id: "ds8",
      topic: "Sorting & Searching",
      question: "Which sorting algorithm is fastest in average case?",
      options: ["Bubble Sort", "Quick Sort", "Insertion Sort", "Selection Sort"],
      correct: "Quick Sort",
    },
    {
      id: "ds9",
      topic: "Arrays & Linked Lists",
      question: "What is the main advantage of linked list over array?",
      options: ["Random access", "Dynamic size", "Cache friendly", "Less memory"],
      correct: "Dynamic size",
    },
    {
      id: "ds10",
      topic: "Trees & Graphs",
      question: "What is a complete binary tree?",
      options: ["All levels filled", "All levels filled except last", "Only left children", "Only right children"],
      correct: "All levels filled except last",
    },
    {
      id: "ds11",
      topic: "Sorting & Searching",
      question: "Which algorithm uses divide and conquer?",
      options: ["Bubble Sort", "Insertion Sort", "Merge Sort", "Selection Sort"],
      correct: "Merge Sort",
    },
    {
      id: "ds12",
      topic: "Stacks & Queues",
      question: "Which data structure is used for recursion?",
      options: ["Queue", "Stack", "Array", "Tree"],
      correct: "Stack",
    },
  ],
  maths: [
    {
      id: "math1",
      topic: "Algebra",
      question: "What is the value of x in: 2x + 5 = 15?",
      options: ["x = 3", "x = 5", "x = 7", "x = 10"],
      correct: "x = 5",
    },
    {
      id: "math2",
      topic: "Algebra",
      question: "Simplify: 3(x + 2) - 2x",
      options: ["x + 6", "x + 2", "5x + 6", "x - 6"],
      correct: "x + 6",
    },
    {
      id: "math3",
      topic: "Calculus",
      question: "What is the derivative of x²?",
      options: ["x", "2x", "x²", "2x²"],
      correct: "2x",
    },
    {
      id: "math4",
      topic: "Calculus",
      question: "What is the integral of 2x?",
      options: ["x²", "x² + C", "2x²", "2x² + C"],
      correct: "x² + C",
    },
    {
      id: "math5",
      topic: "Statistics",
      question: "What is the mean of 4, 8, 12, 16?",
      options: ["8", "10", "12", "14"],
      correct: "10",
    },
    {
      id: "math6",
      topic: "Statistics",
      question: "What is the median of 3, 7, 9, 11, 15?",
      options: ["7", "9", "11", "15"],
      correct: "9",
    },
    {
      id: "math7",
      topic: "Probability",
      question: "What is the probability of getting heads in a coin toss?",
      options: ["0.25", "0.5", "0.75", "1"],
      correct: "0.5",
    },
    {
      id: "math8",
      topic: "Probability",
      question: "What is the probability of rolling a 6 on a die?",
      options: ["1/2", "1/3", "1/6", "1/12"],
      correct: "1/6",
    },
    {
      id: "math9",
      topic: "Algebra",
      question: "What is the solution to x² = 16?",
      options: ["x = 4", "x = ±4", "x = 8", "x = 2"],
      correct: "x = ±4",
    },
    {
      id: "math10",
      topic: "Calculus",
      question: "What is the derivative of sin(x)?",
      options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
      correct: "cos(x)",
    },
    {
      id: "math11",
      topic: "Statistics",
      question: "What measure is most affected by outliers?",
      options: ["Mean", "Median", "Mode", "Range"],
      correct: "Mean",
    },
    {
      id: "math12",
      topic: "Probability",
      question: "What is the probability of drawing an ace from a deck of cards?",
      options: ["1/13", "1/26", "1/52", "4/52"],
      correct: "1/13",
    },
  ],
  physics: [
    {
      id: "phy1",
      topic: "Mechanics",
      question: "What is the SI unit of force?",
      options: ["Joule", "Newton", "Watt", "Pascal"],
      correct: "Newton",
    },
    {
      id: "phy2",
      topic: "Mechanics",
      question: "According to Newton's second law, F = ?",
      options: ["ma", "m/a", "a/m", "m + a"],
      correct: "ma",
    },
    {
      id: "phy3",
      topic: "Mechanics",
      question: "What is the acceleration due to gravity on Earth?",
      options: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11.8 m/s²"],
      correct: "9.8 m/s²",
    },
    {
      id: "phy4",
      topic: "Optics",
      question: "Which type of lens is used to correct myopia?",
      options: ["Convex", "Concave", "Bifocal", "Plano"],
      correct: "Concave",
    },
    {
      id: "phy5",
      topic: "Optics",
      question: "What is the speed of light in vacuum?",
      options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10⁹ m/s", "3 × 10⁷ m/s"],
      correct: "3 × 10⁸ m/s",
    },
    {
      id: "phy6",
      topic: "Optics",
      question: "What happens when light passes from air to water?",
      options: ["Speeds up", "Slows down", "Stops", "Reflects"],
      correct: "Slows down",
    },
    {
      id: "phy7",
      topic: "Electricity",
      question: "What is Ohm's Law?",
      options: ["V = IR", "V = I/R", "V = R/I", "V = I + R"],
      correct: "V = IR",
    },
    {
      id: "phy8",
      topic: "Electricity",
      question: "What is the SI unit of electric current?",
      options: ["Volt", "Ampere", "Ohm", "Watt"],
      correct: "Ampere",
    },
    {
      id: "phy9",
      topic: "Electricity",
      question: "What type of current flows in a battery?",
      options: ["AC", "DC", "Both", "Neither"],
      correct: "DC",
    },
    {
      id: "phy10",
      topic: "Mechanics",
      question: "What is the formula for kinetic energy?",
      options: ["½mv²", "mv²", "m²v", "½m²v"],
      correct: "½mv²",
    },
    {
      id: "phy11",
      topic: "Optics",
      question: "What is the principle behind a mirror?",
      options: ["Refraction", "Reflection", "Diffraction", "Dispersion"],
      correct: "Reflection",
    },
    {
      id: "phy12",
      topic: "Electricity",
      question: "In a series circuit, what remains constant?",
      options: ["Voltage", "Current", "Resistance", "Power"],
      correct: "Current",
    },
  ],
  chemistry: [
    {
      id: "chem1",
      topic: "Organic",
      question: "What is the general formula for alkanes?",
      options: ["CnH2n", "CnH2n+2", "CnH2n-2", "CnHn"],
      correct: "CnH2n+2",
    },
    {
      id: "chem2",
      topic: "Organic",
      question: "Which functional group is present in alcohols?",
      options: ["-OH", "-COOH", "-CHO", "-NH2"],
      correct: "-OH",
    },
    {
      id: "chem3",
      topic: "Organic",
      question: "What is the hybridization of carbon in ethene?",
      options: ["sp", "sp²", "sp³", "dsp²"],
      correct: "sp²",
    },
    {
      id: "chem4",
      topic: "Inorganic",
      question: "What is the atomic number of oxygen?",
      options: ["6", "7", "8", "9"],
      correct: "8",
    },
    {
      id: "chem5",
      topic: "Inorganic",
      question: "Which element has the symbol Na?",
      options: ["Nitrogen", "Sodium", "Nickel", "Neon"],
      correct: "Sodium",
    },
    {
      id: "chem6",
      topic: "Inorganic",
      question: "What is the valency of calcium?",
      options: ["1", "2", "3", "4"],
      correct: "2",
    },
    {
      id: "chem7",
      topic: "Physical",
      question: "What is the pH of a neutral solution?",
      options: ["0", "7", "14", "1"],
      correct: "7",
    },
    {
      id: "chem8",
      topic: "Physical",
      question: "Which state of matter has definite volume but no definite shape?",
      options: ["Solid", "Liquid", "Gas", "Plasma"],
      correct: "Liquid",
    },
    {
      id: "chem9",
      topic: "Physical",
      question: "What is the boiling point of water at sea level?",
      options: ["90°C", "100°C", "110°C", "120°C"],
      correct: "100°C",
    },
    {
      id: "chem10",
      topic: "Organic",
      question: "Which compound is known as marsh gas?",
      options: ["Ethane", "Methane", "Propane", "Butane"],
      correct: "Methane",
    },
    {
      id: "chem11",
      topic: "Inorganic",
      question: "What is the chemical formula of water?",
      options: ["H2O", "H2O2", "HO", "H3O"],
      correct: "H2O",
    },
    {
      id: "chem12",
      topic: "Physical",
      question: "What type of reaction is combustion?",
      options: ["Endothermic", "Exothermic", "Neutral", "Reversible"],
      correct: "Exothermic",
    },
  ],
};

// Function to get random questions from the pool
export function getRandomQuestions(subjectId: string, count: number = 5): QuizQuestion[] {
  const questions = allQuizData[subjectId] || [];
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, questions.length));
}
